### ISSUE TITLE
Several questions about multiselect

### ISSUE THREAD

**Issue by wongzigii** [vzsg/rxswift-multiselect-example#1]
Hi, @vzsg Thanks for your awesome example.
However, I have encountered two questions and trying to figure out at these several days:

1.  How to manually select all button at once?

2. How to select all button initially and then unselect the specific one?

````swift
struct ViewModel {

    init(products: [Product]) {
        self.state = selectedSubject.asObserver()
            .scan(Set()) { (acc: Set<Product>, item: Product) in
                var acc = acc
                if acc.contains(item) {
                    acc.remove(item)
                } else {
                    acc.insert(item)
                }
                return acc
            }
            // start with initial product
            .startWith(Set(products))
            .asDriver(onErrorJustReturn: Set())
    }
}
````

I have tried putting the products into the `startWith` function, this seems like working at first glance.(In fact, the set is empty actually, that the question) However, if you then selected anyone button, the set would only contain that one you just selected, and the remains would become the unselected state.

**Comment by vzsg** [comment]
Hi. I'm glad you found it useful. :)

Using `startWith` was a good idea, but that's not the only point you need to change. Change the seed parameter of the scan operator too:

```
.scan(Set()) <-- that set
```

With that extra step in place, you can implement both of your scenarios easily.

---

Things are different if the list of products is reactive. Then I would invert what the Set means: instead of the enabled, I would store the disabled items, and start with an empty set to have everything selected on the start.

**Comment by wongzigii** [comment]
Thanks for your help! Just need to think it reactively. 💡

**Comment by wongzigii** [comment]
@vzsg Sorry but one more question, If I need to refresh the collectionView after submitting the selected items to server, How can I reset the all the state to unselected? 

Note: after submitting the data and pulling the latest data from server, the cell is still observing the old state from viewModel.
